build:
	go build
	go install

uninstall:
	kraken-stream-service -service uninstall

install:
	go install
	kraken-stream-service -service install

stop:
	kraken-stream-service -service stop

start:
	kraken-stream-service -service start

clean:
	rm kraken-stream-service
